server:
  port: ${REST_PORT}

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DB}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH_DB}
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

oauth2:
  provider:
    google:
      client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}
      token-uri: https://oauth2.googleapis.com/token
      resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
    github:
      client-id: ${GITHUB_OAUTH_CLIENT_ID}
      client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
      redirect-uri: ${GITHUB_OAUTH_REDIRECT_URI}
      token-uri: https://github.com/login/oauth/access_token
      resource-uri: https://api.github.com/user

logging:
  level:
    org:
      springframework:
        security: DEBUG
