version: "3.9"
services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0.5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - ${REDIS_PORT}:6379

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
