version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - mongodb_networks
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      MONGO_NON_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_NON_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_NON_ROOT_DATABASE: ${MONGODB_AUTH_DB}

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongodb_networks
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:${MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}

  kafka-01:
    extends:
      file: docker-compose.skeleton.yml
      service: kafka-common
    ports:
      - ${KAFKA_1_PORT}:9094
    environment:
      KAFKA_CFG_BROKER_ID: 0
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-01:9093,1@kafka-02:9093,2@kafka-03:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-01:9092,EXTERNAL://127.0.0.1:10000
    networks:
      - kafka_network
    volumes:
      - kafka01:/bitnami/kafka

  kafka-02:
    extends:
      file: docker-compose.skeleton.yml
      service: kafka-common
    ports:
      - ${KAFKA_2_PORT}:9094
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-01:9093,1@kafka-02:9093,2@kafka-03:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-02:9092,EXTERNAL://127.0.0.1:10001
    networks:
      - kafka_network
    volumes:
      - kafka02:/bitnami/kafka

  kafka-03:
    extends:
      file: docker-compose.skeleton.yml
      service: kafka-common
    ports:
      - ${KAFKA_3_PORT}:9094
    environment:
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-01:9093,1@kafka-02:9093,2@kafka-03:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-03:9092,EXTERNAL://127.0.0.1:10002
    networks:
      - kafka_network
    volumes:
      - kafka03:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local-Kraft-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-01:9092,kafka-02:9092,kafka-03:9092
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED=true
    depends_on:
      - kafka-01
      - kafka-02
      - kafka-03
    networks:
      - kafka_network

networks:
  kafka_network:
  mongodb_networks:

volumes:
  mongodb-data:
  kafka01:
  kafka02:
  kafka03:
