version: "3.9"
services:
  redis:
    image: redis:7.0.5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6379
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - ${REDIS_PORT}:6379

volumes:
  redis-data:
    driver: local
